<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridCatMarca.aspx.cs" Inherits="CapaPresentacion.gridCatMarca" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2>Catálogo de marcas (catálogo primario)</h2>
    <br />
    <br />
    <asp:Button ID="btnRetornar" runat="server" CssClass="btn btn-block btn-warning" Text="Registrar nueva marca" Font-Size="Large" ForeColor="White" PostBackUrl="~/CatMarca.aspx" ToolTip="Devolverse al catálogo marcas" />
    <asp:GridView ID="dtgMostrarMarca" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" OnRowCommand="dtgMostrarMarca_RowDeleting" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="idMarca" DataSourceID="catMarcas" ForeColor="Black" GridLines="Horizontal" OnSelectedIndexChanged="dtgMostrarMarca_SelectedIndexChanged" AllowSorting="True" ToolTip="Marcas guardadas en la base de datos">
        <Columns>
            <asp:BoundField DataField="idMarca" HeaderText="Id marca" InsertVisible="False" ReadOnly="True" SortExpression="idMarca" />
            <asp:BoundField DataField="nombreMarca" HeaderText="Nombre de la marca" SortExpression="nombreMarca" />                    
        </Columns>
        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
        <HeaderStyle BackColor="#0a1c2e" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F7F7F7" />
        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
        <SortedDescendingCellStyle BackColor="#E5E5E5" />
        <SortedDescendingHeaderStyle BackColor="#0a1c2e" />
    </asp:GridView>
    <asp:SqlDataSource ID="catMarcas" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>"  SelectCommand="SELECT * FROM [catMarcas]" DeleteCommand="DELETE FROM [catMarcas] WHERE [idMarca] = @idMarca" UpdateCommand="UPDATE [catMarcas] SET [nombreMarca] = @nombreMarca WHERE [idMarca] = @idMarca"></asp:SqlDataSource>
    </div>
    </asp:Content>
