<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridCatEmpleado.aspx.cs" Inherits="CapaPresentacion.catalogos.gridCatEmpleado" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2><strong>Empleados</strong></h2>
        <br />
        <asp:Button ID="btnRetornar" runat="server" CssClass="btn btn-warning btn-block" Text="Agregar nuevo empleado" Font-Size="Large" ForeColor="White" PostBackUrl="~/catEmpleados.aspx" ToolTip="Retorna a la página de agregar empleado" />
        <asp:GridView ID="dtgMostrarEmpleados" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="idEmpleado" DataSourceID="catEmpleado" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Horizontal">
            <Columns>
                <asp:BoundField DataField="idEmpleado" HeaderText="Id empleado" InsertVisible="False" ReadOnly="True" SortExpression="idEmpleado" />
                <asp:BoundField DataField="numCedula" HeaderText="Número de cédula" SortExpression="numCedula" />
                <asp:BoundField DataField="primerNombre" HeaderText="Primer nombre" SortExpression="primerNombre" />
                <asp:BoundField DataField="primerApellido" HeaderText="Primer apellido" SortExpression="primerApellido" />
                <asp:BoundField DataField="fechaEntrada" HeaderText="Fecha entrada" SortExpression="fechaEntrada" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#0a1c2e" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#0a1c2e" />
        </asp:GridView>
        <asp:SqlDataSource ID="catEmpleado" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catEmpleados]" DeleteCommand="DELETE FROM [catEmpleados] WHERE [idEmpleado] = @idEmpleado" UpdateCommand="UPDATE [catEmpleados] SET [numCedula] = @numCedula, [primerNombre] = @primerNombre, [primerApellido] = @primerApellido, [fechaEntrada] = @fechaEntrada WHERE [idÉmpleado] = @idEmpleado"></asp:SqlDataSource>
    </div>
</asp:Content>
