<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridTblCompras.aspx.cs" Inherits="CapaPresentacion.tablas.gridTblCompras" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2><strong>Registro de compras</strong></h2>
        <br />
        <asp:Button ID="btnRetornar" CssClass="btn  btn-warning btn-block" runat="server" Text="Hacer nueva compra" OnClick="btnRetornar_Click" Font-Bold="True" Font-Size="Large" ForeColor="White" />
        <br />
        <asp:GridView ID="dtgCompras" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" DataKeyNames="idCompra" DataSourceID="compra" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Horizontal">
            <Columns>
                <asp:BoundField DataField="idCompra" HeaderText="Id compra" InsertVisible="False" ReadOnly="True" SortExpression="idCompra" />
                <asp:BoundField DataField="fecha" HeaderText="Fecha" SortExpression="fecha" />
                <asp:TemplateField HeaderText="Id proveedor" SortExpression="idProveedor">
                    <EditItemTemplate>
                         <asp:DropDownList ID="drpIdProveedor" CssClass="form-control" runat="server" DataSourceID="idProveedor" DataTextField="nombreProveedor" DataValueField="idProveedor" SelectedValue='<%# Bind("idProveedor") %>'></asp:DropDownList>
                         <asp:SqlDataSource ID="idProveedor" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catProveedores]"></asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("idProveedor") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Id empleado" SortExpression="idEmpleado">
                    <EditItemTemplate>
                       <asp:DropDownList ID="drpIdEmpleado" CssClass="form-control" runat="server" DataSourceID="empleado" DataTextField="primerNombre" DataValueField="idEmpleado" SelectedValue='<%# Bind("idEmpleado") %>'></asp:DropDownList>
                       <asp:SqlDataSource ID="empleado" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catEmpleados]"></asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("idEmpleado") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="articulo" HeaderText="Artículo" SortExpression="articulo" />
                <asp:BoundField DataField="cantidad" HeaderText="Cantidad" SortExpression="cantidad" />
                <asp:BoundField DataField="precio" HeaderText="Precio" SortExpression="precio" />
                <asp:BoundField DataField="iva" HeaderText="IVA" SortExpression="iva" />
                <asp:BoundField DataField="total" HeaderText="Total" SortExpression="total" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#0a1c2e" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#0a1c2e" />
        </asp:GridView>
        <asp:SqlDataSource ID="compra" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [tblCompras]" DeleteCommand="delete from[tblCompras] Where [idCompra] = @idCompra" UpdateCommand="UPDATE [tblCompras] SET [fecha] = @fecha, [idProveedor] = @idProveedor, [idEmpleado] = @idEmpleado, [articulo] = @articulo, [cantidad] = @cantidad, [precio] = @precio, [iva] = @iva, [total] = @total WHERE [idCompra] = @idCompra"></asp:SqlDataSource>
    </div>
</asp:Content>
