<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridCatClientes.aspx.cs" Inherits="CapaPresentacion.catalogos.gridCatClientes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2>Clientes</h2>
        <br />
        <asp:Button ID="btnRetornar" runat="server" CssClass="btn btn-block btn-warning" Text="Agregar nuevo cliente" Font-Bold="True" Font-Size="Large" ForeColor="White" PostBackUrl="~/catClientes.aspx" ToolTip="Agregar un nuevo cliente" />
        <asp:GridView ID="dtgVerClientes" CssClass="table table-bordered " runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="idCliente" DataSourceID="catClientes" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Horizontal">
            <Columns>
                <asp:BoundField DataField="idCliente" HeaderText="Id cliente" InsertVisible="False" ReadOnly="True" SortExpression="idCliente" />
                <asp:BoundField DataField="numCedula" HeaderText="Número de cédula" SortExpression="numCedula" />
                <asp:BoundField DataField="primerNombre" HeaderText="Primer nombre" SortExpression="primerNombre" />
                <asp:BoundField DataField="primerApellido" HeaderText="Primer apellido" SortExpression="primerApellido" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#0a1c2e" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#0a1c2e" />
        </asp:GridView>
        <asp:SqlDataSource ID="catClientes" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [tblClientes]" DeleteCommand="DELETE FROM [tblClientes] WHERE [idCliente] = @idCliente" UpdateCommand="UPDATE [tblClientes] SET [numCedula] = @numCedula, [primerNombre] = @primerNombre, [primerApellido] = @primerApellido WHERE [idCliente] = @idCliente"></asp:SqlDataSource>
    </div>
</asp:Content>
