<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridTblVentas.aspx.cs" Inherits="CapaPresentacion.tablas.gridTblVentas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style2 {
            font-size: large;
        }
    </style>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <label><strong><span class="auto-style2">Registro de ventas</span></strong></label>
        <br />
        <asp:Button ID="btnRetornar" runat="server" CssClass="btn btn-block btn-warning" Text="Hacer nueva venta" Font-Bold="True" Font-Size="Large" ForeColor="White" PostBackUrl="~/tblVentas.aspx" ToolTip="Agregar una nueva venta" />
        <br />
        <asp:GridView ID="dtgVerVentas" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="idVentas" DataSourceID="ventas" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Horizontal">
            <Columns>
                <asp:BoundField DataField="idVentas" HeaderText="Id ventas" InsertVisible="False" ReadOnly="True" SortExpression="idVentas" />
                <asp:BoundField DataField="fecha" HeaderText="Fecha" SortExpression="fecha" />               
                <asp:TemplateField HeaderText="Id Cliente" SortExpression="idCliente">
                    <EditItemTemplate>
                         <asp:DropDownList ID="drpIdCliente" CssClass="form-control" runat="server" DataSourceID="cliente" DataTextField="idCliente" DataValueField="idCliente" SelectedValue='<%# Bind("idCliente") %>'></asp:DropDownList>
                         <asp:SqlDataSource ID="cliente" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [tblClientes]"></asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("idCliente") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Id empleado" SortExpression="idEmpleado">
                    <EditItemTemplate>
                        <asp:DropDownList ID="drpIdEmpleado" CssClass="form-control" runat="server" DataSourceID="empleado" DataTextField="primerNombre" DataValueField="idEmpleado" SelectedValue='<%# Bind("idEmpleado") %>'></asp:DropDownList>
            <asp:SqlDataSource ID="empleado" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catEmpleados]"></asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("idEmpleado") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Artículo" SortExpression="idArticulo">
                    <EditItemTemplate>
                        <asp:DropDownList ID="drpArt" CssClass="form-control" runat="server" DataSourceID="art" DataTextField="nombreArticulo" DataValueField="idArticulo" SelectedValue='<%# Bind("idArticulo") %>'></asp:DropDownList>
            <asp:SqlDataSource ID="art" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catArticulos]"></asp:SqlDataSource>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("idArticulo") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="cantidad" HeaderText="Cantidad" SortExpression="cantidad" />
                <asp:BoundField DataField="precio" HeaderText="Precio" SortExpression="precio" />
                <asp:BoundField DataField="iva" HeaderText="I.V.A" SortExpression="iva" />
                <asp:BoundField DataField="total" HeaderText="Total" SortExpression="total" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#0a1c2e" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#0a1c2e" />
        </asp:GridView>
        
        <asp:SqlDataSource ID="ventas" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" DeleteCommand="DELETE FROM [tblVentas] WHERE [idVentas] = @idVentas" UpdateCommand="  UPDATE [tblVentas] SET [fecha] = @fecha, [idCliente] = @idCliente, [idEmpleado] = @idEmpleado, [idArticulo] = @idArticulo, [cantidad] = @cantidad, [precio] = @precio, [iva] = @iva, [total] = @total WHERE [idVentas] = @idVentas" SelectCommand="SELECT * FROM [tblVentas]"></asp:SqlDataSource>
    </div>
</asp:Content>
