<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridCatArticulos.aspx.cs" Inherits="CapaPresentacion.gridCatArticulos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <label><h2>Catálogo artículos ( catálogo secundario)</h2></label>
    <br />
    <br />
    <div class="container">
        <asp:GridView ID="dtgMostrarArticulos" CssClass="table table-stripped" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="idArticulo" DataSourceID="catArticulo" ForeColor="Black" GridLines="Horizontal">
        <Columns>
            <asp:BoundField DataField="idArticulo" HeaderText="idArticulo" InsertVisible="False" ReadOnly="True" SortExpression="idArticulo" />
            <asp:BoundField DataField="nombreArticulo" HeaderText="nombreArticulo" SortExpression="nombreArticulo" />
            <asp:BoundField DataField="idMarca" HeaderText="idMarca" SortExpression="idMarca" />

        </Columns>
        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
        <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F7F7F7" />
        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
        <SortedDescendingCellStyle BackColor="#E5E5E5" />
        <SortedDescendingHeaderStyle BackColor="#242121" />
    </asp:GridView>
    </div>
    <asp:SqlDataSource ID="catArticulo" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catArticulos]" DeleteCommand="DELETE FROM [catArticulos]  WHERE [idArticulo] = @idArticulo" UpdateCommand="UPDATE [catArticulos] SET [nombreArticulo] = @nombreArticulo, [idMarca] = @idMarca WHERE [idArticulo] = @idArticulo"></asp:SqlDataSource>
</asp:Content>
