<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridCatProveedor.aspx.cs" Inherits="CapaPresentacion.catalogos.gridCatProveedor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2><strong>Proveedores</strong></h2>

        <asp:GridView ID="dtgMostrarProveedores" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" DataKeyNames="idProveedor" DataSourceID="catProveedor" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CaptionAlign="Top">
            <Columns>
                <asp:BoundField DataField="idProveedor" HeaderText="Id proveedor" InsertVisible="False" ReadOnly="True" SortExpression="idProveedor" />
                <asp:BoundField DataField="nombreProveedor" HeaderText="Nombre proveedor" SortExpression="nombreProveedor" />
                <asp:BoundField DataField="correo" HeaderText="Correo" SortExpression="correo" />
                <asp:BoundField DataField="telefono" HeaderText="Teléfono" SortExpression="telefono" />
                <asp:BoundField DataField="ciudad" HeaderText="Ciudad" SortExpression="ciudad" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="catProveedor" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catProveedores]" DeleteCommand="DELETE FROM [catProveedores] WHERE [idProveedor] = @idProveedor" UpdateCommand="UPDATE [catProveedores] SET [nombreProveedor] = @nombreProveedor, [correo] = @correo, [telefono] = @telefono, [ciudad] = @ciudad WHERE [idProveedor] = @idProveedor"></asp:SqlDataSource>
    </div>
</asp:Content>
