<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridCatClientes.aspx.cs" Inherits="CapaPresentacion.catalogos.gridCatClientes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <h2>Clientes</h2>
        <br />
        <asp:GridView ID="dtgVerClientes" CssClass="table table-bordered table-dark" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="idCliente" DataSourceID="catClientes">
            <Columns>
                <asp:BoundField DataField="idCliente" HeaderText="idCliente" InsertVisible="False" ReadOnly="True" SortExpression="idCliente" />
                <asp:BoundField DataField="numCedula" HeaderText="numCedula" SortExpression="numCedula" />
                <asp:BoundField DataField="primerNombre" HeaderText="primerNombre" SortExpression="primerNombre" />
                <asp:BoundField DataField="primerApellido" HeaderText="primerApellido" SortExpression="primerApellido" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="catClientes" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [tblClientes]" DeleteCommand="DELETE FROM [tblClientes] WHERE [idCliente] = @idCliente" UpdateCommand="UPDATE [tblClientes] SET [numCedula] = @numCedula, [primerNombre] = @primerNombre, [primerApellido] = @primerApellido WHERE [idCliente] = @idCliente"></asp:SqlDataSource>
    </div>
</asp:Content>
