<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridCatEmpleado.aspx.cs" Inherits="CapaPresentacion.catalogos.gridCatEmpleado" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <label><h2><strong>Empleados</strong></h2></label>
        <br />
        <asp:GridView ID="dtgMostrarEmpleados" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="idEmpleado" DataSourceID="catEmpleado">
            <Columns>
                <asp:BoundField DataField="idEmpleado" HeaderText="Id empleado" InsertVisible="False" ReadOnly="True" SortExpression="idEmpleado" />
                <asp:BoundField DataField="numCedula" HeaderText="Número de cédula" SortExpression="numCedula" />
                <asp:BoundField DataField="primerNombre" HeaderText="Primer nombre" SortExpression="primerNombre" />
                <asp:BoundField DataField="primerApellido" HeaderText="Primer apellido" SortExpression="primerApellido" />
                <asp:BoundField DataField="fechaEntrada" HeaderText="Fecha entrada" SortExpression="fechaEntrada" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="catEmpleado" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" SelectCommand="SELECT * FROM [catEmpleados]" DeleteCommand="DELETE FROM [catEmpleados] WHERE [idEmpleado] = @idEmpleado" UpdateCommand="UPDATE [catEmpleados] SET [numCedula] = @numCedula, [primerNombre] = @primerNombre, [primerApellido] = @primerApellido, [fechaEntrada] = @fechaEntrada WHERE [idÉmpleado] = @idEmpleado"></asp:SqlDataSource>
    </div>
</asp:Content>
