//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catEmpleados
    {
        public catEmpleados()
        {
            this.tblCompras = new HashSet<tblCompras>();
            this.tblVentas = new HashSet<tblVentas>();
        }
    
        public int idEmpleado { get; set; }
        public string numCedula { get; set; }
        public string primerNombre { get; set; }
        public string primerApellido { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
    
        public virtual ICollection<tblCompras> tblCompras { get; set; }
        public virtual ICollection<tblVentas> tblVentas { get; set; }
    }
}
