//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catProveedores
    {
        public catProveedores()
        {
            this.catArticulos = new HashSet<catArticulos>();
            this.tblCompras = new HashSet<tblCompras>();
        }
    
        public int idProveedor { get; set; }
        public string nombreProveedor { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string ciudad { get; set; }
    
        public virtual ICollection<catArticulos> catArticulos { get; set; }
        public virtual ICollection<tblCompras> tblCompras { get; set; }
    }
}
