<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridTblVentas.aspx.cs" Inherits="CapaPresentacion.tablas.gridTblVentas" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <label>Registro de ventas</label>
        <br />
        <asp:GridView ID="dtgVerVentas" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="idVentas" DataSourceID="ventas">
            <Columns>
                <asp:BoundField DataField="idVentas" HeaderText="idVentas" InsertVisible="False" ReadOnly="True" SortExpression="idVentas" />
                <asp:BoundField DataField="fecha" HeaderText="fecha" SortExpression="fecha" />
                <asp:BoundField DataField="idCliente" HeaderText="idCliente" SortExpression="idCliente" />
                <asp:BoundField DataField="idEmpleado" HeaderText="idEmpleado" SortExpression="idEmpleado" />
                <asp:BoundField DataField="cantidad" HeaderText="cantidad" SortExpression="cantidad" />
                <asp:BoundField DataField="precio" HeaderText="precio" SortExpression="precio" />
                <asp:BoundField DataField="iva" HeaderText="iva" SortExpression="iva" />
                <asp:BoundField DataField="total" HeaderText="total" SortExpression="total" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="ventas" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" DeleteCommand="DELETE FROM [tblVentas] WHERE [idVentas] = @idVentas" UpdateCommand="UPDATE [tblVentas] SET [fecha] = @fecha WHERE [idVentas] = @idVentas" SelectCommand="SELECT * FROM [tblVentas]"></asp:SqlDataSource>
    </div>
</asp:Content>
