<%@ Page Title="" Language="C#" MasterPageFile="~/Maestra.Master" AutoEventWireup="true" CodeBehind="gridTblCompras.aspx.cs" Inherits="CapaPresentacion.tablas.gridTblCompras" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <label>Compras</label>
        <asp:GridView ID="dtgCompras" CssClass="table table-bordered" runat="server" AutoGenerateColumns="False" DataKeyNames="idCompra" DataSourceID="compra" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <Columns>
                <asp:BoundField DataField="idCompra" HeaderText="idCompra" InsertVisible="False" ReadOnly="True" SortExpression="idCompra" />
                <asp:BoundField DataField="fecha" HeaderText="fecha" SortExpression="fecha" />
                <asp:BoundField DataField="idProveedor" HeaderText="idProveedor" SortExpression="idProveedor" />
                <asp:BoundField DataField="idCliente" HeaderText="idCliente" SortExpression="idCliente" />
                <asp:BoundField DataField="idEmpleado" HeaderText="idEmpleado" SortExpression="idEmpleado" />
                <asp:BoundField DataField="cantidad" HeaderText="cantidad" SortExpression="cantidad" />
                <asp:BoundField DataField="precio" HeaderText="precio" SortExpression="precio" />
                <asp:BoundField DataField="iva" HeaderText="iva" SortExpression="iva" />
                <asp:BoundField DataField="total" HeaderText="total" SortExpression="total" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="compra" runat="server" ConnectionString="<%$ ConnectionStrings:AlmacenTecnoConnectionString %>" DeleteCommand="delete from[tblCompras] Where [idCompra] = @idCompra" UpdateCommand="UPDATE [tblCompras] SET [fecha] = @fecha, [idProveedor] = @idProveedor, [idCliente] = @idCliente, [idEmpleado] = @idEmpleado WHERE [idCompra] = @idCompra" SelectCommand="SELECT * FROM [tblCompras]"></asp:SqlDataSource>
    </div>
</asp:Content>
